struct DailyUnits {
    pub time: String,
    pub weathercode: String,
    pub temperature_2m_max: String,
    pub temperature_2m_min: String,
    pub temperature_2m_mean: String,
    pub apparent_temperature_max: String,
    pub apparent_temperature_min: String,
    pub apparent_temperature_mean: String,
    pub sunrise: String,
    pub sunset: String,
    pub shortwave_radiation_sum: String,
    pub precipitation_sum: String,
    pub precipitation_hours: String,
    pub windspeed_10m_max: String,
    pub windgusts_10m_max: String,
    pub winddirection_10m_dominant: String,
    pub et0_fao_evapotranspiration: String,
}

struct Daily {
    pub time: Vec<String>,
    pub weathercode: Vec<i64>,
    pub temperature_2m_max: Vec<f64>,
    pub temperature_2m_min: Vec<f64>,
    pub temperature_2m_mean: Vec<f64>,
    pub apparent_temperature_max: Vec<f64>,
    pub apparent_temperature_min: Vec<f64>,
    pub apparent_temperature_mean: Vec<f64>,
    pub sunrise: Vec<String>,
    pub sunset: Vec<String>,
    pub shortwave_radiation_sum: Vec<f64>,
    pub precipitation_sum: Vec<f64>,
    pub precipitation_hours: Vec<i64>,
    pub windspeed_10m_max: Vec<f64>,
    pub windgusts_10m_max: Vec<f64>,
    pub winddirection_10m_dominant: Vec<i64>,
    pub et0_fao_evapotranspiration: Vec<f64>,
}

struct OpenMeteo {
    pub lantitude: f64,
    pub longitude: f64,
    pub generationtime_ms: u64,
    pub utc_offset_seconds: i64,
    pub timezone: String,
    pub timezone_abbreviation: String,
    pub elevation: i64,
    pub daily: Daily,
    pub daily_units: DailyUnits,
}
